---
title: "ERA-Search-Protocols-Draft"
author: "Pete Steward, Todd Rosenstock, Christine Lamanna"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ERA-Search-Protocols-Draft}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## ERA Literature Search Protocol

This document describes the search terms and process used to discover literature for the ERA data (formely known as the Climate Smart Agriculture (CSA) Compendium)

Also see:
* [The Scientific Basis of Climate-Smart Agriculture: A Systematic Review Protocol](https://cgspace.cgiar.org/handle/10568/70967)
* [Climate-Smart Agriculture Compendium 2019 Reference Guide](https://docs.google.com/document/d/1_7XyQlkmI1XLQfzhcRUltGYGjM5myuYOuR6EZXeRegM)

### Search Strings
Search components consisted of three strings: 1) practices; 2) outcomes; and 3) locations ([see Strings section](#Strings)). Due to the large number of outcomes we split search terms into separate strings for ‘productivity’, ‘adaptation’, and ‘mitigation’ outcomes. Within each of the components strings search terms were combined with the Boolean OR operator. Practices and locations strings were combined with each of the outcome strings to give three query string combinations for input into WoS and Scopus. The titles and abstracts of returned references were exported and the screening workflow managed in EndNote. Any duplicate records were removed.

### Screening search results
We used a two-stage screening strategy to determine the relevance of articles returned from search strings to our primary research question. In stage one, article abstracts, and titles were screened according to our predetermined inclusion criteria for practices, outcomes, and locations of interest ([Table 1](#T1)). In stage two, the full texts for those abstracts meeting the initial inclusion criteria were downloaded and screened by the same eligibility criteria.

#### Stage 1: Title and abstract screening
In order to ensure inter-reviewer agreement, iterative rounds of pilot screening were conducted on 100 abstracts to ensure that reviewer decisions met the minimum Cohen’s kappa statistic of 0.6. Each reviewer was then assigned a practice theme, and conducted screening based on the inclusion criteria ([Table 1](#T1)). In the 2013 search (1970-2013) of the 144,767 references identified in the search, 12,803 (8.8%) met the inclusion criteria (or could not be excluded) based on title and abstract screening.

##### Table 1: Inclusion/exclusion criteria {#T1}
Inclusion criteria                               | Exclusion description                                      
-------------------------------------------------|-------------------------------------------------
**Practices**|
  Relevant to one of the selected themes$^1$|  Not relevant to one of the selected themes
  Includes one of the selected practices$^1$|  Relevant to the selected themes, but does not include one of the selected practices
**Outcomes**|
  Reports data relevant to at least one of the selected CSA outcomes$^2$ | Does not report on any indicators for any of the selected CSA outcomes
**Location**|
  Study takes place in or is directly relevant to developing countries|   Study is not focused on developing countries
**Design**|
  Study includes primary data|    Study uses only secondary data, is a review, or is a meta-analysis
  Study includes field collected data|    Study includes only model generated data
  Comparators used in the study|    No use of controls
  Study is at farm or field scale. We can still include studies that present a result averaged across multiple farm or field scale observations.| Study is at larger spatial scale and does not report farm or field level data. 

$^1$ *See `ERAg::PracticeCodes` for details on practices*  
$^2$ *See `ERAg::OutcomeCodes` for details on  outcomes*

#### Stage 2: Full text screening
All articles that passed the title and abstract screening were sourced in full text. This secondary screening considered all criteria but focused largely on the criteria less commonly described in titles and abstracts, such as outcomes, comparators and the presence of primary data. The full text screening for the 2013 search (1970-2013) resulted in a final library of 7,311 references (5.1% of the initial search results) that met all of our inclusion criteria, and forms the basis of this review. This final library was later complemented by two systematic recursive searches: one conducted using the reference lists of each publication in the library that was conducted in Africa, and another conducted using the reference lists of each publication obtained using mitigation search strings (which identified an additional 799 publications). The resulting dataset contained 8,610 references of which 2014 were from Africa.   

**2013-2018 Update**   
The data extraction procedure was repeated with an improved extraction protocol and training. The search & screening was repeated in 2018 covering the years 2013-2018 and African nations. The 2014 African publications that passed full screening from the 2013 search were added to the 2013-2018 title & abstract screened papers for full-text screening and extraction.  

**2019 Updates**  
*pre-2019*: “Greenhouse” and “Lab” experiments conducted in a controlled, non-field setting are only relevant for greenhouse gas emission studies.  
*2019 onwards*: Any outcomes from studies using commercial greenhouses in a field situation (i.e., one that mirrors actual production conditions) should be included. For example, this may include greenhouse production of tomatoes or horticultural crops. 

### Search strings {#Strings}
Terms used when searching Web of Science (WoS) or Scopus databases.  

WoS search used a topic search (TS) and Scopus a TITLE-ABS-KEY() search.  
Search hits were limited to English language and articles.  
Two searches were conducted one in 2013 and another in 2018-19.

**IMPORTANT:** There are differences in syntax when specifying Wos vs. Scopus search terms

1. Boolean operator `NEAR` and `W/` in WoS and SCOPUS respectively.
2. Use of quotation marks and spacing between words or parenthesis.
3. Wildcards in SCOPUS:
    * revert to typing out both words OR using `*` in place of `$` 
    * in SCOPUS, 2 wildcards can be used `?` or `*`. Use of `?` (question mark) when the word can take many forms e.g `wom?n` to search for `woman` or `women`; `*` (asterisk) used to represent any number of characters (inclusive of numbers) e.g. `comput*` gives `computer`, `compute`, `computerization` etc.).
4. Create a Barrier search string for SCOPUS.
5. Agronomy SCOPUS search string search terms rearrangement.


#### Practice Search Strings
##### Agronomy
###### Scopus <=2013
`TITLE-ABS-KEY("conservation agriculture" OR "direct seed*" OR "direct sowing" OR "direct planting" OR "direct drill" OR "no till*" OR "reduced till*" OR "min* till*" OR "zero till" OR "minimum soil disturbance" OR "limit soil disturbance" OR mulch* OR "permanent soil cover" OR "permanent ground cover" OR ("max* biomass prod*" AND soil) OR "stale seed bed" OR "Integrated soil fertility management" OR "integrated soil nutrient management" OR ("organic residue" AND soil) OR ("fertili$er inputs" AND soil) OR "soil amendment" OR "organic input*" OR "organic amendment*" OR "precision agriculture" OR ("micro-dose" OR "microdosing") OR "fertili$er banding" OR (fertili$er NEAR efficient) OR ("efficient use" NEAR Nitrogen) OR ("efficient use" NEAR phosphorus) OR ("efficient use" NEAR fertili$er) OR ("efficient use" NEAR input) OR (soil NEAR manure) OR (soil NEAR "animal waste") OR (compost* NEAR soil) OR ("Soil organic matter" NEAR management) OR "soil inoculation" OR (soil NEAR biofertili*) OR (soil NEAR lime) OR (soil NEAR bioinput) OR (soil NEAR biosolid) OR (soil NEAR biochar) OR "rock fertili$er" OR "small-scale irrigation" OR "water saving irrigat*" OR "drip irrigation" OR "micro irrigation" OR "trickle irrigation" OR rainfed OR ("micro catchment" OR microcatchment) OR (pits NEAR "water harvesting") OR "dam" OR "stone lines" OR "sprinkler irrigation" OR "terrac*" OR "fanya" NEAR "terrace*" OR (bund AND contour) OR "soil and water conservation" OR "grass strips" OR "vetiver grass" OR "on-farm water retention" OR "water storage" OR "water harvesting" OR "water collection" OR "water conservation" OR ((rainwater OR rainfall OR precipitation) NEAR harvesting) OR ((rainwater OR rainfall OR precipitation) NEAR collection) OR ((rainwater OR rainfall OR precipitation) NEAR storage) OR ((water OR rainwater OR moisture) AND conservation) NEAR "in situ") OR "deficit irrigation" OR "partial root drying" OR "supplement irrigation" or "supplementary irrigation" OR "Lift irrigation" OR "alternate partial root zone irrigation" OR ("alternate wetting and drying" NEAR rice) OR "midseason drainage" OR "system of rice intensification" OR SRI OR (transplan* NEAR rice) OR "green manure" OR "cover crop*" OR covercrop* OR "ground cover" OR groundcover OR "legum* cover" OR "plant residue*" or "crop residue*" OR ((intercrop* OR "inter crop*") NEAR legum*) OR (("nitrogen fix*" NEAR intercrop*) OR ("N fix*" NEAR intercrop*) OR ("N2 fix*" NEAR intercrop*)) OR (("nitrogen fix*" NEAR "intercrop*") OR ("N fix*" NEAR "intercrop*") OR ("N2 fix*" NEAR "intercrop*")) OR "improv* fallow*" OR ("heat resistant cultivar" OR "heat resistant crop") OR "drought resistant cultivar" OR "drought resistant crop" OR "heat resistant cultivar" OR "heat resistant crop" OR "salt resistant cultivar" OR "salt resistant crop" OR "cropping system diversification" OR "crop diversification" OR "diversif* crop*" OR "crop rotation*" OR ("crop succession" OR "crop sequence" OR "crop pattern") OR "local cultivar*" OR "local crop*" or "local accession*" OR polycultur* OR ((farm* OR "production system") NEAR divers*) OR "double crop*" OR "relay crop*" OR "Integrated Pest management" OR "IPM" OR "integrated pest control" OR ((pest* OR insect* OR weeds* OR pathogen*) NEAR "action threshold*") OR ((pest* OR insect* OR weed* OR pathogen*) NEAR "econom* threshold*" OR “crop-livestock” OR “basin irrig*” OR “saline irrig*” OR “improved groundwater management” OR “fertigation” OR “micronutrient” OR “microdosing” OR “micro-dosing” OR “inorganic fertilizer” OR “diversion ditch” OR “bunds” OR “dibble stick” OR “disc-plant*” OR (strip NEAR tillage) OR “ripping” OR (stubble NEAR tillage) OR “ridge and furrow” OR “pitting” OR ((zai OR zay OR matengo) NEAR pits) OR (conservation NEAR tillage))`

######  Scopus 2013-18
`TITLE-ABS-KEY ("conservation agriculture" OR "direct seed*" OR "direct sowing" OR "direct planting" OR "direct drill" OR "no till*" OR "reduced till*" OR "min* till*" OR "zero till" OR "minimum soil disturbance" OR "limit soil disturbance" OR mulch* OR "permanent soil cover" OR "permanent ground cover" OR ("max* biomass prod*" AND soil) OR "stale seed bed" OR "Integrated soil fertility management" OR "integrated soil nutrient management" OR ("organic residue" AND soil) OR ("fertili*er inputs" AND soil) OR "soil amendment" OR "organic input*" OR "organic amendment*" OR "precision agriculture" OR ("micro-dose" OR "microdosing") OR "fertili*er banding" OR (fertili*er W/ efficient) OR ("efficient use" W/ nitrogen) OR ("efficient use" W/ phosphorus) OR ("efficient use" W/ fertili*er) OR ("efficient use" W/ input) OR (soil W/ manure) OR (soil W/ "animal waste") OR (compost* W/ soil) OR ("Soil organic matter" W/ management) OR "soil inoculation" OR (soil W/ biofertili*) OR (soil W/ lime) OR (soil W/ bioinput) OR (soil W/ biosolid) OR (soil W/ biochar) OR "rock fertili*er" OR "small-scale irrigation" OR "water saving irrigat*" OR "drip irrigation" OR "micro irrigation" OR "trickle irrigation" OR rainfed OR ("micro catchment" OR microcatchment) OR (pits W/ "water harvesting") OR "dam" OR "stone lines" OR "sprinkler irrigation" OR "terrac*" OR "fanya" W/ "terrace*" OR (bund AND contour) OR "soil and water conservation" OR "grass strips" OR "vetiver grass" OR "on-farm water retention" OR "water storage" OR "water harvesting" OR "water collection" OR "water conservation" OR ((rainwater OR rainfall OR precipitation) W/ harvesting) OR ((rainwater OR rainfall OR precipitation) W/ collection) OR ((rainwater OR rainfall OR precipitation) W/ storage) OR ((water OR rainwater OR moisture) AND conservation) W/ "in situ") OR "deficit irrigation" OR "partial root drying" OR "supplement irrigation" OR "supplementary irrigation" OR "Lift irrigation" OR "alternate partial root zone irrigation" OR ("alternate wetting and drying" W/ rice) OR "midseason drainage" OR "system of rice intensification" OR sri OR (transplan* W/ rice) OR "green manure" OR "cover crop*" OR covercrop* OR "ground cover" OR groundcover OR "legum* cover" OR "plant residue*" OR "crop residue*" OR ((intercrop* OR "inter crop*") W/ legum*) OR (("nitrogen fix*" W/ intercrop*) OR ("N fix*" W/ intercrop*) OR ("N2 fix*" W/ intercrop*)) OR (("nitrogen fix*" W/ "intercrop*") OR ("N fix*" W/ "intercrop*") OR ("N2 fix*" W/ "intercrop*")) OR "improv* fallow*" OR ("heat resistant cultivar" OR "heat resistant crop") OR "drought resistant cultivar" OR "drought resistant crop" OR "heat resistant cultivar" OR "heat resistant crop" OR "salt resistant cultivar" OR "salt resistant crop" OR "cropping system diversification" OR "crop diversification" OR "diversif* crop*" OR "crop rotation*" OR ("crop succession" OR "crop sequence" OR "crop pattern") OR "local cultivar*" OR "local crop*" OR "local accession*" OR polycultur* OR ((farm* OR "production system") W/ divers*) OR "double crop*" OR "relay crop*" OR "Integrated Pest management" OR "IPM" OR "integrated pest control" OR ((pest* OR insect* OR weeds* OR pathogen*) W/ "action threshold*") OR ((pest* OR insect* OR weed* OR pathogen*) W/ "econom* threshold*" OR "crop-livestock" OR "basin irrig*" OR "saline irrig*" OR "improved groundwater management" OR "fertigation" OR "micronutrient" OR "microdosing" OR "micro-dosing" OR "inorganic fertilizer" OR "diversion ditch" OR "bunds" OR "dibble stick" OR "disc-plant*" OR (strip W/ tillage) OR "ripping" OR (stubble W/ tillage) OR "ridge and furrow" OR "pitting" OR ((zai OR zay OR matengo) W/ pits) OR (conservation W/ tillage)) AND (LIMIT-TO (PUBYEAR, 2018) OR LIMIT-TO (PUBYEAR, 2017) OR LIMIT-TO (PUBYEAR, 2016) OR LIMIT-TO (PUBYEAR, 2015) OR LIMIT-TO (PUBYEAR, 2014) OR LIMIT-TO (PUBYEAR, 2013)) AND (LIMIT-TO (DOCTYPE, "ar")) AND (LIMIT-TO (LANGUAGE, "English"))`

###### WoS <=2013
`TS=("conservation agriculture" OR "direct seed*" OR "direct sowing" OR "direct planting" OR "direct drill" OR "no till*" OR "reduced till*" OR "min* till*" OR "zero till" OR "minimum soil disturbance" OR "limit soil disturbance" OR mulch* OR "permanent soil cover" OR "permanent ground cover" OR ("max* biomass prod*" AND soil) OR "stale seed bed" OR "Integrated soil fertility management" OR "integrated soil nutrient management" OR ("organic residue" AND soil) OR ("fertili$er inputs" AND soil) OR "soil amendment" OR "organic input*" OR "organic amendment*" OR "precision agriculture" OR ("micro-dose" OR "microdosing") OR "fertili$er banding" OR (fertili$er NEAR efficient) OR ("efficient use" NEAR Nitrogen) OR ("efficient use" NEAR phosphorus) OR ("efficient use" NEAR fertili$er) OR ("efficient use" NEAR input) OR (soil NEAR manure) OR (soil NEAR "animal waste") OR (compost* NEAR soil) OR ("Soil organic matter" NEAR management) OR "soil inoculation" OR (soil NEAR biofertili*) OR (soil NEAR lime) OR (soil NEAR bioinput) OR (soil NEAR biosolid) OR (soil NEAR biochar) OR "rock fertili$er" OR "small-scale irrigation" OR "water saving irrigat*" OR "drip irrigation" OR "micro irrigation" OR "trickle irrigation" OR rainfed OR ("micro catchment" OR microcatchment) OR (pits NEAR "water harvesting") OR "dam" OR "stone lines" OR "sprinkler irrigation" OR "terrac*" OR ("fanya" NEAR "terrace*") OR (bund AND contour) OR "soil and water conservation" OR "grass strips" OR "vetiver grass" OR "on-farm water retention" OR "water storage" OR "water harvesting" OR "water collection" OR "water conservation" OR ((rainwater OR rainfall OR precipitation) NEAR harvesting) OR ((rainwater OR rainfall OR precipitation) NEAR collection) OR ((rainwater OR rainfall OR precipitation) NEAR storage) OR (((water OR rainwater OR moisture) AND conservation) NEAR "in situ") OR "deficit irrigation" OR "partial root drying" OR "supplement irrigation" or "supplementary irrigation" OR "Lift irrigation" OR "alternate partial root zone irrigation" OR ("alternate wetting and drying" NEAR rice) OR "midseason drainage" OR "system of rice intensification" OR SRI OR (transplan* NEAR rice) OR "green manure" OR "cover crop*" OR covercrop* OR "ground cover" OR groundcover OR "legum* cover" OR "plant residue*" or "crop residue*" OR ((intercrop* OR "inter crop*") NEAR legum*) OR (("nitrogen fix*" NEAR intercrop*) OR ("N fix*" NEAR intercrop*) OR ("N2 fix*" NEAR intercrop*)) OR (("nitrogen fix*" NEAR "intercrop*") OR ("N fix*" NEAR "intercrop*") OR ("N2 fix*" NEAR "intercrop*")) OR "improv* fallow*" OR ("heat resistant cultivar" OR "heat resistant crop") OR "drought resistant cultivar" OR "drought resistant crop" OR "heat resistant cultivar" OR "heat resistant crop" OR "salt resistant cultivar" OR "salt resistant crop" OR "cropping system diversification" OR "crop diversification" OR "diversif* crop*" OR "crop rotation*" OR ("crop succession" OR "crop sequence" OR "crop pattern") OR "local cultivar*" OR "local crop*" or "local accession*" OR polycultur* OR ((farm* OR "production system") NEAR divers*) OR "double crop*" OR "relay crop*" OR "Integrated Pest management" OR "IPM" OR "integrated pest control" OR ((pest* OR insect* OR weeds* OR pathogen*) NEAR "action threshold*") OR ((pest* OR insect* OR weed* OR pathogen*) NEAR "econom* threshold*") AND LANGUAGE: (English) AND DOCUMENT` `TYPES: (Article)`  
`Indexes=SCI-EXPANDED, SSCI, A&HCI, ESCI Timespan=1970-2013`  

###### WoS 2013-2018
`(TS=("conservation agriculture" OR "direct seed*" OR "direct sowing" OR "direct planting" OR "direct drill" OR "no till*" OR "reduced till*" OR "min* till*" OR "zero till" OR "minimum soil disturbance" OR "limit soil disturbance" OR mulch* OR "permanent soil cover" OR "permanent ground cover" OR ("max* biomass prod*" AND soil) OR "stale seed bed" OR "Integrated soil fertility management" OR "integrated soil nutrient management" OR ("organic residue" AND soil) OR ("fertili$er inputs" AND soil) OR "soil amendment" OR "organic input*" OR "organic amendment*" OR "precision agriculture" OR ("micro-dose" OR "microdosing") OR "fertili$er banding" OR (fertili$er NEAR efficient) OR ("efficient use" NEAR Nitrogen) OR ("efficient use" NEAR phosphorus) OR ("efficient use" NEAR fertili$er) OR ("efficient use" NEAR input) OR (soil NEAR manure) OR (soil NEAR "animal waste") OR (compost* NEAR soil) OR ("Soil organic matter" NEAR management) OR "soil inoculation" OR (soil NEAR biofertili*) OR (soil NEAR lime) OR (soil NEAR bioinput) OR (soil NEAR biosolid) OR (soil NEAR biochar) OR "rock fertili$er" OR "small-scale irrigation" OR "water saving irrigat*" OR "drip irrigation" OR "micro irrigation" OR "trickle irrigation" OR rainfed OR ("micro catchment" OR microcatchment) OR (pits NEAR "water harvesting") OR "dam" OR "stone lines" OR "sprinkler irrigation" OR "terrac*" OR ("fanya" NEAR "terrace*") OR (bund AND contour) OR "soil and water conservation" OR "grass strips" OR "vetiver grass" OR "on-farm water retention" OR "water storage" OR "water harvesting" OR "water collection" OR "water conservation" OR ((rainwater OR rainfall OR precipitation) NEAR harvesting) OR ((rainwater OR rainfall OR precipitation) NEAR collection) OR ((rainwater OR rainfall OR precipitation) NEAR storage) OR ((water OR rainwater OR moisture) AND conservation NEAR "in situ") OR "deficit irrigation" OR "partial root drying" OR "supplement irrigation" or "supplementary irrigation" OR "Lift irrigation" OR "alternate partial root zone irrigation" OR ("alternate wetting and drying" NEAR rice) OR "midseason drainage" OR "system of rice intensification" OR SRI OR (transplan* NEAR rice) OR "green manure" OR "cover crop*" OR covercrop* OR "ground cover" OR groundcover OR "legum* cover" OR "plant residue*" or "crop residue*" OR ((intercrop* OR "inter crop*") NEAR legum*) OR (("nitrogen fix*" NEAR intercrop*) OR ("N fix*" NEAR intercrop*) OR ("N2 fix*" NEAR intercrop*)) OR (("nitrogen fix*" NEAR "intercrop*") OR ("N fix*" NEAR "intercrop*") OR ("N2 fix*" NEAR "intercrop*")) OR "improv* fallow*" OR ("heat resistant cultivar" OR "heat resistant crop") OR "drought resistant cultivar" OR "drought resistant crop" OR "heat resistant cultivar" OR "heat resistant crop" OR "salt resistant cultivar" OR "salt resistant crop" OR "cropping system diversification" OR "crop diversification" OR "diversif* crop*" OR "crop rotation*" OR ("crop succession" OR "crop sequence" OR "crop pattern") OR "local cultivar*" OR "local crop*" or "local accession*" OR polycultur* OR ((farm* OR "production system") NEAR divers*) OR "double crop*" OR "relay crop*" OR "Integrated Pest management" OR "IPM" OR "integrated pest control" OR ((pest* OR insect* OR weeds* OR pathogen*) NEAR "action threshold*") OR ((pest* OR insect* OR weed* OR pathogen*) NEAR "econom* threshold*") OR "crop-livestock" OR "basin irrig*" OR "saline irrig*" OR "improved groundwater management" OR "fertigation" OR "micronutrient" OR "microdosing" OR "micro-dosing" OR "inorganic fertilizer" OR "diversion ditch" OR "bunds" OR "dibble stick" OR "disc-plant*" OR (strip NEAR tillage) OR "ripping" OR (stubble NEAR tillage) OR "ridge and furrow" OR "pitting" OR (("zai" OR "zay" OR "matengo") NEAR "pits") OR (conservation NEAR tillage))) AND LANGUAGE: (English) AND DOCUMENT TYPES: (Article)`  
`Indexes=SCI-EXPANDED, SSCI, A&HCI, ESCI Timespan=2013-2018`  

##### Agroforestry 
######  Scopus <=2013
`TITLE-ABS-KEY(agr*forest* OR agr*silv* OR agr*hort* OR "evergreen agriculture" OR (parkland* AND agr*) OR "farmer managed natural regeneration" OR "commun* natural resource* management" OR "commun* forest* management" OR taungya OR (("mix* crop*" OR "multi* crop*" OR legum* OR indigenous OR exotic OR introduc* OR domesticat* OR farm* OR medicinal OR nut* OR fruit* OR timber* OR “nitrogen fix*”) NEAR tree) OR (("mix* crop*" OR "multi* crop*" OR legum* OR indigenous OR exotic OR introduc* OR domesticat* OR farm* OR medicinal OR nut* OR fruit* OR timber* OR “nitrogen fix*”) NEAR shrub) OR "alley crop*" OR "alley system*" OR "alley farm*" OR "fertilizer tree*" OR "fertiliser tree*" OR "farm* forest*" OR "tree crop interaction*" OR (((multifunction* OR multipurpos* OR "multi functional*" OR "multi purpos*" OR multistrata OR "multi strata") NEAR tree*) OR ((multifunction* OR multipurpos* OR "multi functional*" OR "multi purpos*" OR multistrata OR "multi strata") NEAR shrub*) OR ((multifunction* OR multipurpos* OR "multi functional*" OR "multi purpos*" OR multistrata OR "multi strata") NEAR farm*) OR ((multifunction* OR multipurpos* OR "multi functional*" OR "multi purpos*" OR multistrata OR "multi strata") NEAR agr*)) OR "woody perennial*" OR "non timber forest product*" OR NTFP* OR "agroforestry tree product*" OR "fruit orchard*" OR "nut orchard*" OR "food forest*" OR woodlot* OR ((tree* OR management) NEAR shad*) OR "overstor* tree*" OR "understor* tree*" OR "understor* crop*" OR (((firewood OR "fire wood" OR fuelwood OR "fuel wood") NEAR tree*) OR ((firewood OR "fire wood" OR fuelwood OR "fuel wood") NEAR shrub*) OR ((firewood OR "fire wood" OR fuelwood OR "fuel wood") NEAR bush*)) OR "boundary plant*" OR "liv* fence*" OR hedgerow* OR "riparian buffer strip*" OR "riparian forest buffer*" OR "buffer zone*" OR windbreak* OR shelterbelt* OR "shelter belt*" OR (((plant* OR farm* OR barrier* OR "buffer strip*") NEAR tree* NEAR contour) OR ((plant* OR farm* OR barrier* OR "buffer strip*") NEAR shrub* NEAR contour)) OR "shifting cultivation" OR "improved fallow*" OR "slash* and burn*" OR "swidden agricult*" OR silv*past* OR silv*arable* OR "cut and carry" OR "tree belt*" OR “pruning” OR “coppicing” OR “agrosilvopasto*”)`

######  Scopus 2013-18
`TITLE-ABS-KEY (agr*forest* OR agr*silv* OR agr*hort* OR "evergreen agriculture" OR (parkland* AND agr*) OR "farmer managed natural regeneration" OR "commun* natural resource* management" OR "commun* forest* management" OR taungya OR (("mix* crop*" OR "multi* crop*" OR legum* OR indigenous OR exotic OR introduc* OR domesticat* OR farm* OR medicinal OR nut* OR fruit* OR timber* OR "nitrogen fix*") W/ tree) OR (("mix* crop*" OR "multi* crop*" OR legum* OR indigenous OR exotic OR introduc* OR domesticat* OR farm* OR medicinal OR nut* OR fruit* OR timber* OR "nitrogen fix*") W/ shrub) OR "alley crop*" OR "alley system*" OR "alley farm*" OR "fertilizer tree*" OR "fertiliser tree*" OR "farm* forest*" OR "tree crop interaction*" OR (((multifunction* OR multipurpos* OR "multi functional*" OR "multi purpos*" OR multistrata OR "multi strata") W/ tree*) OR ((multifunction* OR multipurpos* OR "multi functional*" OR "multi purpos*" OR multistrata OR "multi strata") W/ shrub*) OR ((multifunction* OR multipurpos* OR "multi functional*" OR "multi purpos*" OR multistrata OR "multi strata") W/ farm*) OR ((multifunction* OR multipurpos* OR "multi functional*" OR "multi purpos*" OR multistrata OR "multi strata") W/ agr*)) OR "woody perennial*" OR "non timber forest product*" OR ntfp* OR "agroforestry tree product*" OR "fruit orchard*" OR "nut orchard*" OR "food forest*" OR woodlot* OR ((tree* OR management) W/ shad*) OR "overstor* tree*" OR "understor* tree*" OR "understor* crop*" OR (((firewood OR "fire wood" OR fuelwood OR "fuel wood") W/ tree*) OR ((firewood OR "fire wood" OR fuelwood OR "fuel wood") W/ shrub*) OR ((firewood OR "fire wood" OR fuelwood OR "fuel wood") W/ bush*)) OR "boundary plant*" OR "liv* fence*" OR hedgerow* OR "riparian buffer strip*" OR "riparian forest buffer*" OR "buffer zone*" OR windbreak* OR shelterbelt* OR "shelter belt*" OR (((plant* OR farm* OR barrier* OR "buffer strip*") W/ tree* W/ contour) OR ((plant* OR farm* OR barrier* OR "buffer strip*") W/ shrub* W/ contour)) OR "shifting cultivation" OR "improved fallow*" OR "slash* and burn*" OR "swidden agricult*" OR silv*past* OR silv*arable* OR "cut and carry" OR "tree belt*" OR "pruning" OR "coppicing" OR "agrosilvopasto*") AND (LIMIT-TO (PUBYEAR, 2018) OR LIMIT-TO (PUBYEAR, 2017) OR LIMIT-TO (PUBYEAR, 2016) OR LIMIT-TO (PUBYEAR, 2015) OR LIMIT-TO (PUBYEAR, 2014) OR LIMIT-TO (PUBYEAR, 2013)) AND (LIMIT-TO (DOCTYPE, "ar")) AND (LIMIT-TO (LANGUAGE, "English"))`

###### WoS <=2013
`(TS=(agr*forest* OR agr*silv* OR agr*hort* OR "evergreen agriculture" OR (parkland* AND agr*) OR "farmer managed natural regeneration" OR "commun* natural resource* management" OR "commun* forest* management" OR taungya OR (("mix* crop*" OR "multi* crop*" OR legum* OR indigenous OR exotic OR introduc* OR domesticat* OR farm* OR medicinal OR nut* OR fruit* OR timber*) NEAR tree) OR (("mix* crop*" OR "multi* crop*" OR legum* OR indigenous OR exotic OR introduc* OR domesticat* OR farm* OR medicinal OR nut* OR fruit* OR timber*) NEAR shrub) OR "alley crop*" OR "alley system*" OR "alley farm*" OR "fertilizer tree*" OR "fertiliser tree*" OR "farm* forest*" OR "tree crop interaction*" OR (((multifunction* OR multipurpos* OR "multi functional*" OR "multi purpos*" OR multistrata OR "multi strata") NEAR tree*) OR ((multifunction* OR multipurpos* OR "multi functional*" OR "multi purpos*" OR multistrata OR "multi strata") NEAR shrub*) OR ((multifunction* OR multipurpos* OR "multi functional*" OR "multi purpos*" OR multistrata OR "multi strata") NEAR farm*) OR ((multifunction* OR multipurpos* OR "multi functional*" OR "multi purpos*" OR multistrata OR "multi strata") NEAR agr*)) OR "woody perennial*" OR "non timber forest product*" OR NTFP* OR "agroforestry tree product*" OR "fruit orchard*" OR "nut orchard*" OR "food forest*" OR woodlot* OR ((tree* OR management) NEAR shad*) OR "overstor* tree*" OR "understor* tree*" OR "understor* crop*" OR (((firewood OR "fire wood" OR fuelwood OR "fuel wood") NEAR tree*) OR ((firewood OR "fire wood" OR fuelwood OR "fuel wood") NEAR shrub*) OR ((firewood OR "fire wood" OR fuelwood OR "fuel wood") NEAR bush*)) OR "boundary plant*" OR "liv* fence*" OR hedgerow* OR "riparian buffer strip*" OR "riparian forest buffer*" OR "buffer zone*" OR windbreak* OR shelterbelt* OR "shelter belt*" OR (((plant* OR farm* OR barrier* OR "buffer strip*") NEAR tree* NEAR contour) OR ((plant* OR farm* OR barrier* OR "buffer strip*") NEAR shrub* NEAR contour)) OR "shifting cultivation" OR "improved fallow*" OR "slash* and burn*" OR "swidden agricult*" OR silv*past* OR silv*arable* OR "cut and carry" OR "tree belt*")) AND LANGUAGE: (English) AND DOCUMENT TYPES: (Article)`  
`Indexes=SCI-EXPANDED, SSCI, A&HCI, ESCI Timespan=1970-2013`  

###### WoS 2013-2018
`(TS=(agr*forest* OR agr*silv* OR agr*hort* OR "evergreen agriculture" OR (parkland* AND agr*) OR "farmer managed natural regeneration" OR "commun* natural resource* management" OR "commun* forest* management" OR taungya OR (("mix* crop*" OR "multi* crop*" OR legum* OR indigenous OR exotic OR introduc* OR domesticat* OR farm* OR medicinal OR nut* OR fruit* OR timber* OR “nitrogen fix*”) NEAR tree) OR (("mix* crop*" OR "multi* crop*" OR legum* OR indigenous OR exotic OR introduc* OR domesticat* OR farm* OR medicinal OR nut* OR fruit* OR timber* OR “nitrogen fix*”) NEAR shrub) OR "alley crop*" OR "alley system*" OR "alley farm*" OR "fertilizer tree*" OR "fertiliser tree*" OR "farm* forest*" OR "tree crop interaction*" OR (((multifunction* OR multipurpos* OR "multi functional*" OR "multi purpos*" OR multistrata OR "multi strata") NEAR tree*) OR ((multifunction* OR multipurpos* OR "multi functional*" OR "multi purpos*" OR multistrata OR "multi strata") NEAR shrub*) OR ((multifunction* OR multipurpos* OR "multi functional*" OR "multi purpos*" OR multistrata OR "multi strata") NEAR farm*) OR ((multifunction* OR multipurpos* OR "multi functional*" OR "multi purpos*" OR multistrata OR "multi strata") NEAR agr*)) OR "woody perennial*" OR "non timber forest product*" OR NTFP* OR "agroforestry tree product*" OR "fruit orchard*" OR "nut orchard*" OR "food forest*" OR woodlot* OR ((tree* OR management) NEAR shad*) OR "overstor* tree*" OR "understor* tree*" OR "understor* crop*" OR (((firewood OR "fire wood" OR fuelwood OR "fuel wood") NEAR tree*) OR ((firewood OR "fire wood" OR fuelwood OR "fuel wood") NEAR shrub*) OR ((firewood OR "fire wood" OR fuelwood OR "fuel wood") NEAR bush*)) OR "boundary plant*" OR "liv* fence*" OR hedgerow* OR "riparian buffer strip*" OR "riparian forest buffer*" OR "buffer zone*" OR windbreak* OR shelterbelt* OR "shelter belt*" OR (((plant* OR farm* OR barrier* OR "buffer strip*") NEAR tree* NEAR contour) OR ((plant* OR farm* OR barrier* OR "buffer strip*") NEAR shrub* NEAR contour)) OR "shifting cultivation" OR "improved fallow*" OR "slash* and burn*" OR "swidden agricult*" OR silv*past* OR silv*arable* OR "cut and carry" OR "tree belt*" OR “pruning” OR “coppicing” OR “agrosilvopasto*”)) AND LANGUAGE: (English) AND DOCUMENT TYPES: (Article)`  
`Indexes=SCI-EXPANDED, SSCI, A&HCI, ESCI Timespan=2013-2018`  

##### Livestock

######  Scopus <=2013
`TITLE-ABS-KEY(Livestock OR "mono gastric" OR cattle OR sheep OR goats OR pigs OR poultry OR ruminant OR aquaculture OR fish*) AND ("non-conventional feed" OR "Forage productivity" OR grass OR "pasture additive" OR "grass-legume" OR "feed conversion" OR "feed intake" OR "protein intake" OR "energy intake" OR "feed availability" OR “feed supplement*” OR "energy retention" OR "growth rate" OR "feed acceptability" OR "feeding frequency" OR "stover digestibility" OR "paddock" OR "free*range" OR "hay" OR "silage" OR "fodder shrub*" OR "nomadic" OR pastoral OR "signal*grass" OR (pasture NEAR cerrado) OR "crop residue" OR "animal husbandry" OR "pasture species" OR "crop-pasture" OR "pasture crop*" OR "zero graz*" OR "rotational graz*" OR "conti* graz*" OR "stocking density" OR "organic* livestock" OR "ammonia volatil*" OR "N-retention" OR "cover* manure" OR "biogas capture" OR "Manure acidification" OR "Cover* manure" OR "Manure collection" OR "manure treatment" OR "artificial insemination" OR "trait selection" OR "heat period" OR ovulation OR hybrid OR "desirable traits" OR "progeny test" OR "semen analysis" OR "cross breed*" OR "Aquasilviculture" OR "Integrated multi-trophic aquaculture" OR "Organic Aquaculture" OR "fishing intensity" OR "culture based fishery" OR "vulnerable" OR "susceptible" OR "resistan*" OR "quarantine" OR "antibiotic" OR "vaccine" OR "dewormer" OR "ectoparasite" OR "innoculation" OR “agropasto*” OR (Livestock AND (antistress OR "anti-stress")))`

######  Scopus 2013-18
`TITLE-ABS-KEY((livestock OR "mono gastric" OR cattle OR sheep OR goats OR pigs OR poultry OR ruminant OR aquaculture OR fish*) AND ("non-conventional feed" OR "Forage productivity" OR grass OR "pasture additive" OR "grass-legume" OR "feed conversion" OR "feed intake" OR "protein intake" OR "energy intake" OR "feed availability" OR "feed supplement*" OR "energy retention" OR "growth rate" OR "feed acceptability" OR "feeding frequency" OR "stover digestibility" OR "paddock" OR "free*range" OR "hay" OR "silage" OR "fodder shrub*" OR "nomadic" OR pastoral OR "signal*grass" OR (pasture W/ cerrado) OR "crop residue" OR "animal husbandry" OR "pasture species" OR "crop-pasture" OR "pasture crop*" OR "zero graz*" OR "rotational graz*" OR "conti* graz*" OR "stocking density" OR "organic* livestock" OR "ammonia volatil*" OR "N-retention" OR "cover* manure" OR "biogas capture" OR "Manure acidification" OR "Cover* manure" OR "Manure collection" OR "manure treatment" OR "artificial insemination" OR "trait selection" OR "heat period" OR ovulation OR hybrid OR "desirable traits" OR "progeny test" OR "semen analysis" OR "cross breed*" OR "Aquasilviculture" OR "Integrated multi-trophic aquaculture" OR "Organic Aquaculture" OR "fishing intensity" OR "culture based fishery" OR "vulnerable" OR "susceptible" OR "resistan*" OR "quarantine" OR "antibiotic" OR "vaccine" OR "dewormer" OR "ectoparasite" OR "innoculation" OR "agropasto*" OR (livestock AND (antistress OR "anti-stress")))) AND (LIMIT-TO (PUBYEAR, 2018) OR LIMIT-TO (PUBYEAR, 2017) OR LIMIT-TO (PUBYEAR, 2016) OR LIMIT-TO (PUBYEAR, 2015) OR LIMIT-TO (PUBYEAR, 2014) OR LIMIT-TO (PUBYEAR, 2013)) AND (LIMIT-TO (DOCTYPE, "ar")) AND (LIMIT-TO (LANGUAGE, "English"))`

###### WoS <=2013
`(TS=((Livestock OR "mono gastric" OR cattle OR sheep OR goats OR pigs OR poultry OR ruminant OR aquaculture OR fish*) AND ("non-conventional feed" OR "Forage productivity" OR grass OR "pasture additive" OR "grass-legume" OR "feed conversion" OR "feed intake" OR "protein intake" OR "energy intake" OR "feed availability" OR “feed supplement*” OR "energy retention" OR "growth rate" OR "feed acceptability" OR "feeding frequency" OR "stover digestibility" OR "paddock" OR "free*range" OR "hay" OR "silage" OR "fodder shrub*" OR "nomadic" OR pastoral OR "signal*grass" OR (pasture NEAR cerrado) OR "crop residue" OR "animal husbandry" OR "pasture species" OR "crop-pasture" OR "pasture crop*" OR "zero graz*" OR "rotational graz*" OR "conti* graz*" OR "stocking density" OR "organic* livestock" OR "ammonia volatil*" OR "N-retention" OR "cover* manure" OR "biogas capture" OR "Manure acidification" OR "Cover* manure" OR "Manure collection" OR "manure treatment" OR "artificial insemination" OR "trait selection" OR "heat period" OR ovulation OR hybrid OR "desirable traits" OR "progeny test" OR "semen analysis" OR "cross breed*" OR "Aquasilviculture" OR "Integrated multi-trophic aquaculture" OR "Organic Aquaculture" OR "fishing intensity" OR "culture based fishery" OR "vulnerable" OR "susceptible" OR "resistan*" OR "quarantine" OR "antibiotic" OR "vaccine" OR "dewormer" OR "ectoparasite" OR "innoculation" OR (Livestock AND (antistress OR "anti-stress"))))) AND LANGUAGE: (English) AND DOCUMENT TYPES: (Article)`  
`Indexes=SCI-EXPANDED, SSCI, A&HCI, ESCI Timespan=1970-2013`

###### WoS 2013-2018
`(TS=((Livestock OR "mono gastric" OR cattle OR sheep OR goats OR pigs OR poultry OR ruminant OR aquaculture OR fish*) AND ("non-conventional feed" OR "Forage productivity" OR grass OR "pasture additive" OR "grass-legume" OR "feed conversion" OR "feed intake" OR "protein intake" OR "energy intake" OR "feed availability" OR “feed supplement*” OR "energy retention" OR "growth rate" OR "feed acceptability" OR "feeding frequency" OR "stover digestibility" OR "paddock" OR "free*range" OR "hay" OR "silage" OR "fodder shrub*" OR "nomadic" OR pastoral OR "signal*grass" OR (pasture NEAR cerrado) OR "crop residue" OR "animal husbandry" OR "pasture species" OR "crop-pasture" OR "pasture crop*" OR "zero graz*" OR "rotational graz*" OR "conti* graz*" OR "stocking density" OR "organic* livestock" OR "ammonia volatil*" OR "N-retention" OR "cover* manure" OR "biogas capture" OR "Manure acidification" OR "Cover* manure" OR "Manure collection" OR "manure treatment" OR "artificial insemination" OR "trait selection" OR "heat period" OR ovulation OR hybrid OR "desirable traits" OR "progeny test" OR "semen analysis" OR "cross breed*" OR "Aquasilviculture" OR "Integrated multi-trophic aquaculture" OR "Organic Aquaculture" OR "fishing intensity" OR "culture based fishery" OR "vulnerable" OR "susceptible" OR "resistan*" OR "quarantine" OR "antibiotic" OR "vaccine" OR "dewormer" OR "ectoparasite" OR "innoculation" OR “agropasto*” OR (Livestock AND (antistress OR "anti-stress"))))) AND LANGUAGE: (English) AND DOCUMENT TYPES: (Article)`  
`Indexes=SCI-EXPANDED, SSCI, A&HCI, ESCI Timespan=2013-2018`

######  Post Harvest

######  Scopus <=2013
`TITLE-ABS-KEY("post harvest loss" OR "food loss" OR "food waste" OR (improved NEAR "harvest technique*") OR "harvest technolog*" OR "harvest maturity" OR (improved NEAR "harvest method*") OR "harvest time*" OR "post harvest storage" OR ("post harvest" NEAR silo*) OR "storage bin" OR "hermetic systems" OR (storage NEAR warehouse) OR ("improve* stor*" AND (Crop OR grain OR harvest OR feed)) OR "on farm storage" OR "off farm storage" OR ("post-harvest" AND (pest OR insect) AND control) OR (("post harvest" OR storage) AND cooling) OR (("post harvest" OR storage) AND drying) OR ("post harvest" AND (preservation AND drying OR salting OR dehydration)))`

######  Scopus 2013-18
`TITLE-ABS-KEY ("post harvest loss" OR "food loss" OR "food waste" OR (improved W/ "harvest technique*") OR "harvest technolog*" OR "harvest maturity" OR (improved W/ "harvest method*") OR "harvest time*" OR "post harvest storage" OR ("post harvest" W/ silo*) OR "storage bin" OR "hermetic systems" OR (storage W/ Warehouse) OR ("improve* stor*" AND (crop OR grain OR harvest OR feed)) OR "on farm storage" OR "off farm storage" OR ("post-harvest" AND (pest OR insect) AND control) OR (("post harvest" OR storage) AND cooling) OR (("post harvest" OR storage) AND drying) OR ("post harvest" AND (preservation AND drying OR salting OR dehydration))) AND (LIMIT-TO (PUBYEAR, 2018) OR LIMIT-TO (PUBYEAR, 2017) OR LIMIT-TO (PUBYEAR, 2016) OR LIMIT-TO (PUBYEAR, 2015) OR LIMIT-TO (PUBYEAR, 2014) OR LIMIT-TO (PUBYEAR, 2013)) AND (LIMIT-TO (DOCTYPE, "ar")) AND (LIMIT-TO (LANGUAGE, "English"))`

###### WoS <=2013 & 2013-2018
`(TS=("post harvest loss" OR "food loss" OR "food waste" OR (improved NEAR "harvest technique*") OR "harvest technolog*" OR "harvest maturity" OR (improved NEAR "harvest method*") OR "harvest time*" OR "post harvest storage" OR ("post harvest" NEAR silo*) OR "storage bin" OR "hermetic systems" OR (storage NEAR warehouse) OR ("improve* stor*" AND (Crop OR grain OR harvest OR feed)) OR "on farm storage" OR "off farm storage" OR ("post-harvest" AND (pest OR insect) AND control) OR (("post harvest" OR storage) AND cooling) OR (("post harvest" OR storage) AND drying) OR ("post harvest" AND (preservation AND drying OR salting OR dehydration)))) AND LANGUAGE: (English) AND DOCUMENT TYPES: (Article)`  
`Indexes=SCI-EXPANDED, SSCI, A&HCI, ESCI Timespan=1970-2013`  

OR 

`Indexes=SCI-EXPANDED, SSCI, A&HCI, ESCI Timespan=2013-2018`

#####  Energy Systems
######  Scopus <=2013
`TITLE-ABS-KEY(cookstove* OR "cook* stove*" OR "improv* stove*" OR "anaerobic digest*" OR "anaerobic ferment*" OR "bio* digest*" OR "biodigest*")`

######  Scopus 2013-18
`TITLE-ABS-KEY  (cookstove* OR "cook* stove*" OR "improv* stove*" OR "anaerobic digest*" OR "anaerobic ferment*" OR "bio* digest*" OR "biodigest*") AND (LIMIT-TO (PUBYEAR, 2018) OR LIMIT-TO (PUBYEAR, 2017) OR LIMIT-TO (PUBYEAR, 2016) OR LIMIT-TO (PUBYEAR, 2015) OR LIMIT-TO (PUBYEAR, 2014) OR LIMIT-TO (PUBYEAR, 2013)) AND (LIMIT-TO (DOCTYPE, "ar")) AND (LIMIT-TO (LANGUAGE, "English")) `

###### WoS <=2013 & 2013-2018
`(TS=((cookstove* OR "cook* stove*" OR "improv* stove*" OR "anaerobic digest*" OR "anaerobic ferment*" OR "bio* digest*" OR "biodigest*"))) AND LANGUAGE: (English) AND DOCUMENT TYPES: (Article)`  
`Indexes=SCI-EXPANDED, SSCI, A&HCI, ESCI Timespan=1970-2013`

OR 

`Indexes=SCI-EXPANDED, SSCI, A&HCI, ESCI Timespan=2013-2018`

####  Outcome Search Strings
#####  Production
######  Scopus <=2013
`TITLE-ABS-KEY (yield* OR "yield stability" OR output* OR outturn OR product* OR efficien* OR tonne* OR ton OR tons OR bags OR bushel* OR harvest* OR "crop production" OR "crop productivity" OR "grain fill*" OR "dry matter" OR protein* OR "feed consumption" OR "feed conversion rate*" OR "feed conversion efficiency" OR "reproduction rate*" OR "lambing rate*" OR "calving rate*" OR "kidding rate*" OR "litter size*" OR litre* OR liter* OR "kg/ha" OR "kilogram* per hectare" OR "kg per hectare" OR "turnoff rate*" OR "live weight gain*" OR "liveweight gain*" OR "carcase weight*" OR "carcass weight*" OR "dressed weight*" OR egg* OR catch* OR "maximum sustainable catch*") OR (variability OR variance OR "standard deviation" OR variation) OR ((income* OR receipt* OR payment* OR revenue*) OR "change inventory") OR (cost* OR expense* OR debit*) OR ("capital destruction" OR tax OR ("interest rate*") OR lease) OR (profit* OR "gross margin*" OR ("earnings before interest tax") OR "operating profit*" OR "bottom line" OR "net income*" OR "gross income*" OR "net farm income*") OR (return* OR "net present value*" OR "gross added value*" OR "net added value*" OR "net worth" OR "equity" OR "payback period*" OR "breakeven period*" OR "break even period*" OR "cost benefit analy*" OR "benefit cost analy*" OR "cost effectiv* analy*" OR "opportunity cost*" OR "econom* evaluation*" OR "econom* valuation*" OR "econom* analy*" OR "economic impact*" OR "discount* cash flow*" OR "partial budget*") OR ((("direct use" OR "passive use" OR "non market" OR contingent OR consumptive OR consumption OR subsistence OR livelihood*) AND (value* OR valuation*)) OR "willingness to pay") OR ((labour* OR labor* OR worker* OR employee*) OR ("full time equivalent*" OR "working day*" OR "man day*" OR "man power") OR (“benefit cost ratio” OR “benefit-cost ratio” OR “cost benefit ratio” OR “cost-benefit ratio”))`

######  Scopus 2013-18
`TITLE-ABS-KEY ((yield* OR "yield stability" OR output* OR outturn OR product* OR efficien* OR tonne* OR ton OR tons OR bags OR bushel* OR harvest* OR "crop production" OR "crop productivity" OR "grain fill*" OR "dry matter" OR protein* OR "feed consumption" OR "feed conversion rate*" OR "feed conversion efficiency" OR "reproduction rate*" OR "lambing rate*" OR "calving rate*" OR "kidding rate*" OR "litter size*" OR litre* OR liter* OR "kg/ha" OR "kilogram* per hectare" OR "kg per hectare" OR "turnoff rate*" OR "live weight gain*" OR "liveweight gain*" OR "carcase weight*" OR "carcass weight*" OR "dressed weight*" OR egg* OR catch* OR "maximum sustainable catch*") OR (variability OR variance OR "standard deviation" OR variation) OR ((income* OR receipt* OR payment* OR revenue*) OR "change inventory") OR (cost* OR expense* OR debit*) OR ("capital destruction" OR tax OR ("interest rate*") OR lease) OR (profit* OR "gross margin*" OR ("earnings before interest tax") OR "operating profit*" OR "bottom line" OR "net income*" OR "gross income*" OR "net farm income*") OR (return* OR "net present value*" OR "gross added value*" OR "net added value*" OR "net worth" OR "equity" OR "payback period*" OR "breakeven period*" OR "break even period*" OR "cost benefit analy*" OR "benefit cost analy*" OR "cost effectiv* analy*" OR "opportunity cost*" OR "econom* evaluation*" OR "econom* valuation*" OR "econom* analy*" OR "economic impact*" OR "discount* cash flow*" OR "partial budget*") OR ((("direct use" OR "passive use" OR "non market" OR contingent OR consumptive OR consumption OR subsistence OR livelihood*) AND (value* OR valuation*)) OR "willingness to pay") OR ((labour* OR labor* OR worker* OR employee*) OR ("full time equivalent*" OR "working day*" OR "man day*" OR "man power") OR ("benefit cost ratio" OR "benefit-cost ratio" OR "cost benefit ratio" OR "cost-benefit ratio"))) AND (LIMIT-TO (DOCTYPE, "ar")) AND (LIMIT-TO (PUBYEAR, 2018) OR LIMIT-TO (PUBYEAR, 2017) OR LIMIT-TO (PUBYEAR, 2016) OR LIMIT-TO (PUBYEAR, 2015) OR LIMIT-TO (PUBYEAR, 2014) OR LIMIT-TO (PUBYEAR, 2013)) AND (LIMIT-TO (LANGUAGE, "English")) `

###### WoS <=2013
`(TS=((yield* OR "yield stability" OR output* OR outturn OR product* OR efficien* OR tonne* OR ton OR tons OR bags OR bushel* OR harvest* OR "crop production" OR "crop productivity" OR "grain fill*" OR "dry matter" OR protein* OR "feed consumption" OR "feed conversion rate*" OR "feed conversion efficiency" OR "reproduction rate*" OR "lambing rate*" OR "calving rate*" OR "kidding rate*" OR "litter size*" OR litre* OR liter* OR "kg/ha" OR "kilogram* per hectare" OR "kg per hectare" OR "turnoff rate*" OR "live weight gain*" OR "liveweight gain*" OR "carcase weight*" OR "carcass weight*" OR "dressed weight*" OR egg* OR catch* OR "maximum sustainable catch*") OR (variability OR variance OR "standard deviation" OR variation) OR ((income* OR receipt* OR payment* OR revenue*) OR "change inventory") OR (cost* OR expense* OR debit*) OR ("capital destruction" OR tax OR ("interest rate*") OR lease) OR (profit* OR "gross margin*" OR ("earnings before interest tax") OR "operating profit*" OR "bottom line" OR "net income*" OR "gross income*" OR "net farm income*") OR (return* OR "net present value*" OR "gross added value*" OR "net added value*" OR "net worth" OR "equity" OR "payback period*" OR "breakeven period*" OR "break even period*" OR "cost benefit analy*" OR "benefit cost analy*" OR "cost effectiv* analy*" OR "opportunity cost*" OR "econom* evaluation*" OR "econom* valuation*" OR "econom* analy*" OR "economic impact*" OR "discount* cash flow*" OR "partial budget*") OR ((("direct use" OR "passive use" OR "non market" OR contingent OR consumptive OR consumption OR subsistence OR livelihood*) AND (value* OR valuation*)) OR "willingness to pay") OR ((labour* OR labor* OR worker* OR employee*) OR ("full time equivalent*" OR "working day*" OR "man day*" OR "man power")))) AND LANGUAGE: (English) AND DOCUMENT TYPES: (Article)`  
`Indexes=SCI-EXPANDED, SSCI, A&HCI, ESCI Timespan=1970-2013`

###### WoS 2013-2018
`(TS=((yield* OR "yield stability" OR output* OR outturn OR product* OR efficien* OR tonne* OR ton OR tons OR bags OR bushel* OR harvest* OR "crop production" OR "crop productivity" OR "grain fill*" OR "dry matter" OR protein* OR "feed consumption" OR "feed conversion rate*" OR "feed conversion efficiency" OR "reproduction rate*" OR "lambing rate*" OR "calving rate*" OR "kidding rate*" OR "litter size*" OR litre* OR liter* OR "kg/ha" OR "kilogram* per hectare" OR "kg per hectare" OR "turnoff rate*" OR "live weight gain*" OR "liveweight gain*" OR "carcase weight*" OR "carcass weight*" OR "dressed weight*" OR egg* OR catch* OR "maximum sustainable catch*") OR (variability OR variance OR "standard deviation" OR variation) OR ((income* OR receipt* OR payment* OR revenue*) OR "change inventory") OR (cost* OR expense* OR debit*) OR ("capital destruction" OR tax OR ("interest rate*") OR lease) OR (profit* OR "gross margin*" OR ("earnings before interest tax") OR "operating profit*" OR "bottom line" OR "net income*" OR "gross income*" OR "net farm income*") OR (return* OR "net present value*" OR "gross added value*" OR "net added value*" OR "net worth" OR "equity" OR "payback period*" OR "breakeven period*" OR "break even period*" OR "cost benefit analy*" OR "benefit cost analy*" OR "cost effectiv* analy*" OR "opportunity cost*" OR "econom* evaluation*" OR "econom* valuation*" OR "econom* analy*" OR "economic impact*" OR "discount* cash flow*" OR "partial budget*") OR ((("direct use" OR "passive use" OR "non market" OR contingent OR consumptive OR consumption OR subsistence OR livelihood*) AND (value* OR valuation*)) OR "willingness to pay") OR ((labour* OR labor* OR worker* OR employee*) OR ("full time equivalent*" OR "working day*" OR "man day*" OR "man power")) OR (“benefit cost ratio” OR “benefit-cost ratio” OR “cost benefit ratio” OR “cost-benefit ratio”))) AND LANGUAGE: (English) AND DOCUMENT TYPES: (Article)`
`Indexes=SCI-EXPANDED, SSCI, A&HCI, ESCI Timespan=2013-2018`

##### Mitigation
######  Scopus <=2013
`TS= ("nitrous oxide" OR N2O OR methane OR CH4 OR "carbon dioxide" OR CO2 OR CO2e OR "CO2 eq" OR "CO2 equivalent" OR emission* OR "greenhouse gas*" OR "global warming potential" OR GWP OR "yield scaled" OR "carbon accumulat*" OR "biomass carbon" OR "carbon stock*" OR "trace gas*" OR "soil carbon sequestration" OR "enteric fermentation" OR "global warming intensity" OR "carbon intensity" OR "emission intensity" OR "carbon footprint" OR "carbon efficiency" OR "atmospheric carbon")`

######  Scopus 2013-18
`TITLE-ABS-KEY ("nitrous oxide" OR n2o OR methane OR ch4 OR "carbon dioxide" OR co2 OR co2e OR "CO2 eq" OR "CO2 equivalent" OR emission* OR "greenhouse gas*" OR "global warming potential" OR gwp OR "yield scaled" OR "carbon accumulat*" OR "biomass carbon" OR "carbon stock*" OR "trace gas*" OR "soil carbon sequestration" OR "enteric fermentation" OR "global warming intensity" OR "carbon intensity" OR "emission intensity" OR "carbon footprint" OR "carbon efficiency" OR "atmospheric carbon") AND (LIMIT-TO (PUBYEAR, 2018) OR LIMIT-TO (PUBYEAR, 2017) OR LIMIT-TO (PUBYEAR, 2016) OR LIMIT-TO (PUBYEAR, 2015) OR LIMIT-TO (PUBYEAR, 2014) OR LIMIT-TO (PUBYEAR, 2013)) AND (LIMIT-TO (DOCTYPE, "ar")) AND (LIMIT-TO (LANGUAGE, "English"))`

###### WoS <=2013 & 2013-2018
`(TS= ("nitrous oxide" OR N2O OR methane OR CH4 OR "carbon dioxide" OR CO2 OR CO2e OR "CO2 eq" OR "CO2 equivalent" OR emission* OR "greenhouse gas*" OR "global warming potential" OR GWP OR "yield scaled" OR "carbon accumulat*" OR "biomass carbon" OR "carbon stock*" OR "trace gas*" OR "soil carbon sequestration" OR "enteric fermentation" OR "global warming intensity" OR "carbon intensity" OR "emission intensity" OR "carbon footprint" OR "carbon efficiency" OR "atmospheric carbon")) AND LANGUAGE: (English) AND DOCUMENT TYPES: (Article)`  
`Indexes=SCI-EXPANDED, SSCI, A&HCI, ESCI Timespan=1970-2013`  

OR 

`Indexes=SCI-EXPANDED, SSCI, A&HCI, ESCI Timespan=2013-2018`

#####  Resilience
######  Scopus <=2013
`TS=((Adapt* OR toleran* OR resilien* OR "adapt* capacity" OR "adapt* management" OR "capacity building" OR "climate vulnerab*" OR "climate risk" OR "climate change" OR "indigenous knowledge" OR "local knowledge" OR "tradition* knowledge" OR "ecolog* knowledge" OR "commun* awareness" OR "commun* assessment*" OR "vulnerab* assessment*" OR "risk assessment*" OR "participatory assessment*" OR "soci* ecological system*" OR "land use change*" OR "global warming" OR "adaptation to climate change " OR "changing climate") AND ("food access" OR kilocalorie* OR "household consumption" OR "food expenditure" OR "total expenditure" OR "consumption expenditure" OR "meals per day" OR "dietary diversity" OR nutrition* OR hunger OR "food security" OR "food scarc*" OR "nutrition* security" OR "food safety" OR malnutrition OR malnourishment OR undernutrition OR undernourishment OR anaemia OR ((smallholder* OR household* OR agricult*) AND diet) OR "food affordab*" OR "food system*" OR "value chain*" OR poverty OR (micronutrient* NEAR food) OR famine OR "food insecurity" OR "food volatility" OR "food consumption*" OR "food intake" OR "food stability" OR "food availab*" OR "food distribut*" OR "food utilization" OR "food utilisation" OR "Shannon* index" OR "Simpson* index" OR "Species richness" OR "Species diversi*" OR "species evenness" OR "species resilien*" OR "crop divers*" OR "cultivar divers*" OR agr*bio*divers* OR biodiversity OR "indigenous species" OR "neglect* species" OR "native species" OR "landscape diversi*" OR "income diversi*" OR "red list*" OR "pest* and pathogen*" OR "population* dynamic*" OR ((livestock* OR crop*) NEAR infestation*) OR "species presence" OR "species resistance" OR "species tolerance" OR "pest cost*" OR "implement* cost*" OR ("yield loss" NEAR cost*) OR susceptib* OR erosion OR runoff OR ((loss* OR formation OR aggregation OR fertility OR cover* OR degrad* OR decline) NEAR Soil) OR landslide OR "land slide*" OR desertification OR degrad* OR deforest* OR "soil organic matter" OR "soil organic carbon" OR "soil biomass" OR "soil humus" OR "water use efficiency" OR "water use" OR "water loss" OR "water waste" OR irrigation OR "water availability" OR "water uptake" OR "water consumption" OR "water conservation" OR "water lifecycle*" OR "water footprint" OR "transpiration rate*" OR "water stress" OR "water utility" OR (water NEAR yield) OR "integrated water resource* management" OR "water recycling" OR "water reuse" OR "water productivity" OR "use efficiency" OR "nutrient balanc*" OR "nutrient flow*" OR "nutrient loss*" OR "nutrient uptake" OR "nutrient enrichment" OR ((potassium OR phosphorus OR nitrogen) NEAR uptake) OR "phosphorus uptake" OR "nitrogen uptake" OR "nutrient accumulation" OR "fertilizer management" OR "eco efficien*" OR "embodied energy" OR "energy flow*" OR "energy balance" OR "energy input*" OR "energy output*" OR (energy NEAR management) OR "energy return on energy investment" OR "energy resource*" OR "energy source*" OR "energy use efficiency" OR "energy footprint*" OR "net energy" OR "energy consumption" OR "energy value*" OR "energy saving*" OR (labour OR labor) OR ("labour saving" OR "labor saving") OR income OR wage OR "cash flow*" OR revenue* OR livelihoods OR "on farm activit*" OR "off farm activit*" OR "income earning means" OR "income earning activities" OR "income diversification" OR "seasonal labo*" OR "direct use" OR "own use" OR "women* group*" OR cooperative* OR "employ* opportunit*" OR (Women OR gender AND ("division of labo*")) OR "gender equality" OR entitlement* OR "gender inequality" OR "gender equity" OR "gender relation*" OR "female livelihoods" OR "female entrepreneur*" OR "female headed household*" OR (female AND participation) OR (women AND budget) OR gender* OR "power relation*" OR "gender vulnerability" OR "gender role*" OR "gender knowledge" OR "gender adapt*" OR "gender asset*" OR "female asset*" OR "female propert*" OR (female NEAR finance) OR (female NEAR credit*) OR (female NEAR capital*) OR (women NEAR capital*) OR (women NEAR forag*) OR (women NEAR harvest*) OR matriarchy OR patriarchy OR empowerment OR "cost revenue*" OR membership* OR "farmer* association*" OR "peasant* association*" OR "farmer* union*" OR "farmer* group*" OR "gender analysis" OR (women NEAR income) OR "women* association*" OR "women* farm* association*") OR “livelihood diversif*” OR “bulk density” OR “water productivity”)`

######  Scopus 2013-18
`TITLE-ABS-KEY ((adapt* OR toleran* OR resilien* OR "adapt* capacity" OR "adapt* management" OR "capacity building" OR "climate vulnerab*" OR "climate risk" OR "climate change" OR "indigenous knowledge" OR "local knowledge" OR "tradition* knowledge" OR "ecolog* knowledge" OR "commun* awareness" OR "commun* assessment*" OR "vulnerab* assessment*" OR "risk assessment*" OR "participatory assessment*" OR "soci* ecological system*" OR "land use change*" OR "global warming" OR "adaptation to climate change " OR "changing climate") AND ("food access" OR kilocalorie* OR "household consumption" OR "food expenditure" OR "total expenditure" OR "consumption expenditure" OR "meals per day" OR "dietary diversity" OR nutrition* OR hunger OR "food security" OR "food scarc*" OR "nutrition* security" OR "food safety" OR malnutrition OR malnourishment OR undernutrition OR undernourishment OR anaemia OR ((smallholder* OR household* OR agricult*) AND diet) OR "food affordab*" OR "food system*" OR "value chain*" OR poverty OR (micronutrient* W/ food) OR famine OR "food insecurity" OR "food volatility" OR "food consumption*" OR "food intake" OR "food stability" OR "food availab*" OR "food distribut*" OR "food utilization" OR "food utilisation" OR "Shannon* index" OR "Simpson* index" OR "Species richness" OR "Species diversi*" OR "species evenness" OR "species resilien*" OR "crop divers*" OR "cultivar divers*" OR agr*bio*divers* OR biodiversity OR "indigenous species" OR "neglect* species" OR "native species" OR "landscape diversi*" OR "income diversi*" OR "red list*" OR "pest* and pathogen*" OR "population* dynamic*" OR ((livestock* OR crop*) W/ infestation*) OR "species presence" OR "species resistance" OR "species tolerance" OR "pest cost*" OR "implement* cost*" OR ("yield loss" W/ cost*) OR susceptib* OR erosion OR runoff OR ((loss* OR formation OR aggregation OR fertility OR cover* OR degrad* OR decline) W/ soil) OR landslide OR "land slide*" OR desertification OR degrad* OR deforest* OR "soil organic matter" OR "soil organic carbon" OR "soil biomass" OR "soil humus" OR "water use efficiency" OR "water use" OR "water loss" OR "water waste" OR irrigation OR "water availability" OR "water uptake" OR "water consumption" OR "water conservation" OR "water lifecycle*" OR "water footprint" OR "transpiration rate*" OR "water stress" OR "water utility" OR (water W/ yield) OR "integrated water resource* management" OR "water recycling" OR "water reuse" OR "water productivity" OR "use efficiency" OR "nutrient balanc*" OR "nutrient flow*" OR "nutrient loss*" OR "nutrient uptake" OR "nutrient enrichment" OR ((potassium OR phosphorus OR nitrogen) W/ uptake) OR "phosphorus uptake" OR "nitrogen uptake" OR "nutrient accumulation" OR "fertilizer management" OR "eco efficien*" OR "embodied energy" OR "energy flow*" OR "energy balance" OR "energy input*" OR "energy output*" OR (energy W/ management) OR "energy return on energy investment" OR "energy resource*" OR "energy source*" OR "energy use efficiency" OR "energy footprint*" OR "net energy" OR "energy consumption" OR "energy value*" OR "energy saving*" OR (labour OR labor) OR ("labour saving" OR "labor saving") OR income OR wage OR "cash flow*" OR revenue* OR livelihoods OR "on farm activit*" OR "off farm activit*" OR "income earning means" OR "income earning activities" OR "income diversification" OR "seasonal labo*" OR "direct use" OR "own use" OR "women* group*" OR cooperative* OR "employ* opportunit*" OR (women OR gender AND ("division of labo*")) OR "gender equality" OR entitlement* OR "gender inequality" OR "gender equity" OR "gender relation*" OR "female livelihoods" OR "female entrepreneur*" OR "female headed household*" OR (female AND participation) OR (women AND budget) OR gender* OR "power relation*" OR "gender vulnerability" OR "gender role*" OR "gender knowledge" OR "gender adapt*" OR "gender asset*" OR "female asset*" OR "female propert*" OR (female W/ finance) OR (female W/ credit*) OR (female W/ capital*) OR (women W/ capital*) OR (women W/ forag*) OR (women W/ harvest*) OR matriarchy OR patriarchy OR empowerment OR "cost revenue*" OR membership* OR "farmer* association*" OR "peasant* association*" OR "farmer* union*" OR "farmer* group*" OR "gender analysis" OR (women W/ income) OR "women* association*" OR "women* farm* association*" OR "livelihood diversif*" OR "bulk density" OR "water productivity")) AND (LIMIT-TO (PUBYEAR, 2018) OR LIMIT-TO (PUBYEAR, 2017) OR LIMIT-TO (PUBYEAR, 2016) OR LIMIT-TO (PUBYEAR, 2015) OR LIMIT-TO (PUBYEAR, 2014) OR LIMIT-TO (PUBYEAR, 2013)) AND (LIMIT-TO (DOCTYPE, "ar")) AND (LIMIT-TO (LANGUAGE, "English")) `

###### WoS <=2013
`(TS=((Adapt* OR toleran* OR resilien* OR "adapt* capacity" OR "adapt* management" OR "capacity building" OR "climate vulnerab*" OR "climate risk" OR "climate change" OR "indigenous knowledge" OR "local knowledge" OR "tradition* knowledge" OR "ecolog* knowledge" OR "commun* awareness" OR "commun* assessment*" OR "vulnerab* assessment*" OR "risk assessment*" OR "participatory assessment*" OR "soci* ecological system*" OR "land use change*" OR "global warming" OR "adaptation to climate change " OR "changing climate") AND ("food access" OR kilocalorie* OR "household consumption" OR "food expenditure" OR "total expenditure" OR "consumption expenditure" OR "meals per day" OR "dietary diversity" OR nutrition* OR hunger OR "food security" OR "food scarc*" OR "nutrition* security" OR "food safety" OR malnutrition OR malnourishment OR undernutrition OR undernourishment OR anaemia OR ((smallholder* OR household* OR agricult*) AND diet) OR "food affordab*" OR "food system*" OR "value chain*" OR poverty OR (micronutrient* NEAR food) OR famine OR "food insecurity" OR "food volatility" OR "food consumption*" OR "food intake" OR "food stability" OR "food availab*" OR "food distribut*" OR "food utilization" OR "food utilisation" OR "Shannon* index" OR "Simpson* index" OR "Species richness" OR "Species diversi*" OR "species evenness" OR "species resilien*" OR "crop divers*" OR "cultivar divers*" OR agr*bio*divers* OR biodiversity OR "indigenous species" OR "neglect* species" OR "native species" OR "landscape diversi*" OR "income diversi*" OR "red list*" OR "pest* and pathogen*" OR "population* dynamic*" OR ((livestock* OR crop*) NEAR infestation*) OR "species presence" OR "species resistance" OR "species tolerance" OR "pest cost*" OR "implement* cost*" OR ("yield loss" NEAR cost*) OR susceptib* OR erosion OR runoff OR ((loss* OR formation OR aggregation OR fertility OR cover* OR degrad* OR decline) NEAR Soil) OR landslide OR "land slide*" OR desertification OR degrad* OR deforest* OR "soil organic matter" OR "soil organic carbon" OR "soil biomass" OR "soil humus" OR "water use efficiency" OR "water use" OR "water loss" OR "water waste" OR irrigation OR "water availability" OR "water uptake" OR "water consumption" OR "water conservation" OR "water lifecycle*" OR "water footprint" OR "transpiration rate*" OR "water stress" OR "water utility" OR (water NEAR yield) OR "integrated water resource* management" OR "water recycling" OR "water reuse" OR "water productivity" OR "use efficiency" OR "nutrient balanc*" OR "nutrient flow*" OR "nutrient loss*" OR "nutrient uptake" OR "nutrient enrichment" OR ((potassium OR phosphorus OR nitrogen) NEAR uptake) OR "phosphorus uptake" OR "nitrogen uptake" OR "nutrient accumulation" OR "fertilizer management" OR "eco efficien*" OR "embodied energy" OR "energy flow*" OR "energy balance" OR "energy input*" OR "energy output*" OR (energy NEAR management) OR "energy return on energy investment" OR "energy resource*" OR "energy source*" OR "energy use efficiency" OR "energy footprint*" OR "net energy" OR "energy consumption" OR "energy value*" OR "energy saving*" OR (labour OR labor) OR ("labour saving" OR "labor saving") OR income OR wage OR "cash flow*" OR revenue* OR livelihoods OR "on farm activit*" OR "off farm activit*" OR "income earning means" OR "income earning activities" OR "income diversification" OR "seasonal labo*" OR "direct use" OR "own use" OR "women* group*" OR cooperative* OR "employ* opportunit*" OR (Women OR gender AND ("division of labo*")) OR "gender equality" OR entitlement* OR "gender inequality" OR "gender equity" OR "gender relation*" OR "female livelihoods" OR "female entrepreneur*" OR "female headed household*" OR (female AND participation) OR (women AND budget) OR gender* OR "power relation*" OR "gender vulnerability" OR "gender role*" OR "gender knowledge" OR "gender adapt*" OR "gender asset*" OR "female asset*" OR "female propert*" OR (female NEAR finance) OR (female NEAR credit*) OR (female NEAR capital*) OR (women NEAR capital*) OR (women NEAR forag*) OR (women NEAR harvest*) OR matriarchy OR patriarchy OR empowerment OR "cost revenue*" OR membership* OR "farmer* association*" OR "peasant* association*" OR "farmer* union*" OR "farmer* group*" OR "gender analysis" OR (women NEAR income) OR "women* association*" OR "women* farm* association*")) AND LANGUAGE: (English) AND DOCUMENT TYPES: (Article)`  
`Indexes=SCI-EXPANDED, SSCI, A&HCI, ESCI Timespan=1970-2013`

###### WoS 2013-2018
`(TS=((Adapt* OR toleran* OR resilien* OR "adapt* capacity" OR "adapt* management" OR "capacity building" OR "climate vulnerab*" OR "climate risk" OR "climate change" OR "indigenous knowledge" OR "local knowledge" OR "tradition* knowledge" OR "ecolog* knowledge" OR "commun* awareness" OR "commun* assessment*" OR "vulnerab* assessment*" OR "risk assessment*" OR "participatory assessment*" OR "soci* ecological system*" OR "land use change*" OR "global warming" OR "adaptation to climate change " OR "changing climate") AND ("food access" OR kilocalorie* OR "household consumption" OR "food expenditure" OR "total expenditure" OR "consumption expenditure" OR "meals per day" OR "dietary diversity" OR nutrition* OR hunger OR "food security" OR "food scarc*" OR "nutrition* security" OR "food safety" OR malnutrition OR malnourishment OR undernutrition OR undernourishment OR anaemia OR ((smallholder* OR household* OR agricult*) AND diet) OR "food affordab*" OR "food system*" OR "value chain*" OR poverty OR (micronutrient* NEAR food) OR famine OR "food insecurity" OR "food volatility" OR "food consumption*" OR "food intake" OR "food stability" OR "food availab*" OR "food distribut*" OR "food utilization" OR "food utilisation" OR "Shannon* index" OR "Simpson* index" OR "Species richness" OR "Species diversi*" OR "species evenness" OR "species resilien*" OR "crop divers*" OR "cultivar divers*" OR agr*bio*divers* OR biodiversity OR "indigenous species" OR "neglect* species" OR "native species" OR "landscape diversi*" OR "income diversi*" OR "red list*" OR "pest* and pathogen*" OR "population* dynamic*" OR ((livestock* OR crop*) NEAR infestation*) OR "species presence" OR "species resistance" OR "species tolerance" OR "pest cost*" OR "implement* cost*" OR ("yield loss" NEAR cost*) OR susceptib* OR erosion OR runoff OR ((loss* OR formation OR aggregation OR fertility OR cover* OR degrad* OR decline) NEAR Soil) OR landslide OR "land slide*" OR desertification OR degrad* OR deforest* OR "soil organic matter" OR "soil organic carbon" OR "soil biomass" OR "soil humus" OR "water use efficiency" OR "water use" OR "water loss" OR "water waste" OR irrigation OR "water availability" OR "water uptake" OR "water consumption" OR "water conservation" OR "water lifecycle*" OR "water footprint" OR "transpiration rate*" OR "water stress" OR "water utility" OR (water NEAR yield) OR "integrated water resource* management" OR "water recycling" OR "water reuse" OR "water productivity" OR "use efficiency" OR "nutrient balanc*" OR "nutrient flow*" OR "nutrient loss*" OR "nutrient uptake" OR "nutrient enrichment" OR ((potassium OR phosphorus OR nitrogen) NEAR uptake) OR "phosphorus uptake" OR "nitrogen uptake" OR "nutrient accumulation" OR "fertilizer management" OR "eco efficien*" OR "embodied energy" OR "energy flow*" OR "energy balance" OR "energy input*" OR "energy output*" OR (energy NEAR management) OR "energy return on energy investment" OR "energy resource*" OR "energy source*" OR "energy use efficiency" OR "energy footprint*" OR "net energy" OR "energy consumption" OR "energy value*" OR "energy saving*" OR (labour OR labor) OR ("labour saving" OR "labor saving") OR income OR wage OR "cash flow*" OR revenue* OR livelihoods OR "on farm activit*" OR "off farm activit*" OR "income earning means" OR "income earning activities" OR "income diversification" OR "seasonal labo*" OR "direct use" OR "own use" OR "women* group*" OR cooperative* OR "employ* opportunit*" OR (Women OR gender AND ("division of labo*")) OR "gender equality" OR entitlement* OR "gender inequality" OR "gender equity" OR "gender relation*" OR "female livelihoods" OR "female entrepreneur*" OR "female headed household*" OR (female AND participation) OR (women AND budget) OR gender* OR "power relation*" OR "gender vulnerability" OR "gender role*" OR "gender knowledge" OR "gender adapt*" OR "gender asset*" OR "female asset*" OR "female propert*" OR (female NEAR finance) OR (female NEAR credit*) OR (female NEAR capital*) OR (women NEAR capital*) OR (women NEAR forag*) OR (women NEAR harvest*) OR matriarchy OR patriarchy OR empowerment OR "cost revenue*" OR membership* OR "farmer* association*" OR "peasant* association*" OR "farmer* union*" OR "farmer* group*" OR "gender analysis" OR (women NEAR income) OR "women* association*" OR "women* farm* association*" OR “livelihood diversif*” OR “bulk density” OR “water productivity”)) AND LANGUAGE: (English) AND DOCUMENT TYPES: (Article)`  
`Indexes=SCI-EXPANDED, SSCI, A&HCI, ESCI Timespan=2013-2018`

##### Region Search String
######  Scopus <=2013
`TS=(Africa OR Algeria OR Angola OR Benin OR Botswana OR "Burkina Faso" OR Burundi OR "Cabo Verde" OR Cameroon OR "Central African Republic" OR CAR OR Chad OR Comoros OR Congo OR "Cote d'Ivoire" OR "Ivory Coast" OR Djibouti OR Egypt OR "Equatorial Guinea" OR Eritrea OR Ethiopia OR Gabon OR Gambia OR Ghana OR Guinea OR Guinea-Bissau OR Kenya OR Lesotho OR Liberia OR Libya OR Madagascar OR Malawi OR Mali OR Mauritania OR Mauritius OR Morocco OR Mozambique OR Namibia OR Niger OR Nigeria OR Rwanda OR "Sao Tome" OR Principe OR Senegal OR Seychelles OR "Sierra Leone" OR Somalia OR "South Africa" OR "South Sudan" OR Sudan OR Swaziland OR Tanzania OR Togo OR Tunisia OR Uganda OR Zambia OR Zimbabwe OR Sahara OR Sub-Sahara OR Sahel)`

######  Scopus 2013-18
`TITLE-ABS-KEY (africa OR algeria OR angola OR benin OR botswana OR "Burkina Faso" OR burundi OR "Cabo Verde" OR cameroon OR "Central African Republic" OR car OR chad OR comoros OR congo OR "Cote d'Ivoire" OR "Ivory Coast" OR djibouti OR egypt OR "Equatorial Guinea" OR eritrea OR ethiopia OR gabon OR gambia OR ghana OR guinea OR guinea-bissau OR kenya OR lesotho OR liberia OR libya OR madagascar OR malawi OR mali OR mauritania OR mauritius OR morocco OR mozambique OR namibia OR niger OR nigeria OR rwanda OR "Sao Tome" OR principe OR senegal OR seychelles OR "Sierra Leone" OR somalia OR "South Africa" OR "South Sudan" OR sudan OR swaziland OR tanzania OR togo OR tunisia OR uganda OR zambia OR zimbabwe OR sahara OR sub-sahara OR sahel) AND (LIMIT-TO (PUBYEAR, 2018) OR LIMIT-TO (PUBYEAR, 2017) OR LIMIT-TO (PUBYEAR, 2016) OR LIMIT-TO (PUBYEAR, 2015) OR LIMIT-TO (PUBYEAR, 2014) OR LIMIT-TO (PUBYEAR, 2013)) AND (LIMIT-TO (DOCTYPE, "ar")) AND (LIMIT-TO (LANGUAGE,   "English"))`
  
###### WoS <=2013 & 2013-2018
`(TS=(Africa OR Algeria OR Angola OR Benin OR Botswana OR "Burkina Faso" OR Burundi OR "Cabo Verde" OR Cameroon OR "Central African Republic" OR CAR OR Chad OR Comoros OR Congo OR "Cote d'Ivoire" OR "Ivory Coast" OR Djibouti OR Egypt OR "Equatorial Guinea" OR Eritrea OR Ethiopia OR Gabon OR Gambia OR Ghana OR Guinea OR Guinea-Bissau OR Kenya OR Lesotho OR Liberia OR Libya OR Madagascar OR Malawi OR Mali OR Mauritania OR Mauritius OR Morocco OR Mozambique OR Namibia OR Niger OR Nigeria OR Rwanda OR "Sao Tome" OR Principe OR Senegal OR Seychelles OR "Sierra Leone" OR Somalia OR "South Africa" OR "South Sudan" OR Sudan OR Swaziland OR Tanzania OR Togo OR Tunisia OR Uganda OR Zambia OR Zimbabwe OR Sahara OR Sub-Sahara OR Sahel)) AND LANGUAGE: (English) AND DOCUMENT TYPES: (Article)`  
`Indexes=SCI-EXPANDED, SSCI, A&HCI, ESCI Timespan=1970-2013`  

OR 

`Indexes=SCI-EXPANDED, SSCI, A&HCI, ESCI Timespan=2013-2018`

##### Search terms not included in 2013 WoS search

PRACTICES:  
“pruning” OR “coppicing” OR “agrosilvopasto*”   

OR “agropasto”   

“crop-livestock” OR “basin irrig*” OR “saline irrig*” OR “improved groundwater management” OR “fertigation” OR “micronutrient” OR “microdosing” OR “micro-dosing” OR “inorganic fertilizer” OR “diversion ditch” OR “bunds” OR “dibble stick” OR “disc-plant*” OR “(strip NEAR tillage) OR “ripping” OR “stubble NEAR tillage” OR “ridge and furrow” OR “pitting” OR “pits NEAR (zai OR zay OR matengo)” OR “(conservation NEAR tillage)”.  

OUTCOMES:  
“benefit cost ratio” OR “benefit-cost ratio” OR “cost benefit ratio” OR “cost-benefit ratio”   

 “livelihood diversif*” OR “bulk density” OR “water productivity”  
